openapi: "3.0.3"

info:
  version: "2.0"
  title: Individuals Dividends Income (MTD)
  description: |
    The following groups of endpoints are stateful in the Sandbox:
    * [Dividends Income](#tag/Dividends-Income)
    * [UK Dividends Income](#tag/UK-Dividends-Income)
    * [Additional Directorship and Dividend Information](#tag/Additional-Directorship-and-Dividend-Information)

    # Send fraud prevention data
    HMRC monitors transactions to help protect your customers' confidential data from criminals and fraudsters. 
    
    <div class="govuk-warning-text warning-icon-fix">
      <span class="govuk-warning-text__icon warning-icon-ui-fix" aria-hidden="true">!</span>
      <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        You are required by law to submit header data for this API. This includes all associated APIs and endpoints.
      </strong>
    </div>
    
    [Check the data you need to send](/guides/fraud-prevention/). You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/2.0) during initial development and as part of your quality assurance checks.
    
    # Mapping APIs to Self Assessment tax return forms
    Some parameters in this API map to box numbers in one or more Self Assessment tax return forms. To learn more and to download this mapping information as a CSV file, go to [income-tax-mtd-changelog/mapping](https://github.com/hmrc/income-tax-mtd-changelog?tab=readme-ov-file#mapping-apis-to-self-assessment-tax-return-forms) on GitHub.

    # Changelog
    You can find the changelog in the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/#readme) on GitHub.
    
    # Support
    
    * Raise non-technical or platform-related issues with the [Software Development Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).
    * Raise technical issues on the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues) GitHub page.

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access

tags:
  - name: Dividends Income
    description: These endpoints allow a user to create, amend, retrieve and delete Dividends

  - name: UK Dividends Income
    description: Resources relating to an individual's uk dividends

# {{#if (enabled 'additional-directorship-dividend')}}
  - name: Additional Directorship and Dividend Information
    description: Provide taxable income for less common types of dividends income
# {{/if}}

paths:
  /individuals/dividends-income/{nino}/{taxYear}:
    $ref: "./dividends.yaml"
  /individuals/dividends-income/uk/{nino}/{taxYear}:
    $ref: "./uk_dividends.yaml"
# {{#if (enabled 'additional-directorship-dividend')}}
  /individuals/dividends-income/directorship/{nino}/{taxYear}/{employmentId}:
    $ref: "./additional_directorship_dividend.yaml"
# {{/if}}
